### ISSUE TITLE
Additive Manufacturing recipe

### ISSUE THREAD

**Issue by wilkus27** [openstax/recipes#109]
Content: col10000 content03

**Comment by MartaSztuka** [comment]
@wilkus27 Book in general look's ok, but there are some minor problems:
1. Chapter outline header is unstyled
2. Space between Outline and 'Introduction to Certification...' is small
![Screenshot from 2021-11-04 11-27-30.png]
(https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d8917eb9-4c66-4ff4-852f-87e7b4f14406)
3. Figures (not placeholders) are too small 
![Screenshot from 2021-11-04 11-34-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8b04911f-1fad-438c-be27-f09c11db22d6)
4. One Figure is outside the margin ![Screenshot from 2021-11-04 11-36-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6b84d071-34c3-4f00-a962-103f60875de8)

**Comment by wilkus27** [comment]
For Chapter Outline and Solutions I created separate issues:

1. https://github.com/openstax/cnx-recipes/issues/4198
2. https://github.com/openstax/cnx-recipes/issues/4201

About figures, @lwtchu should we worry about that or it is just test content, so it'll be fixed in the future?
