### ISSUE TITLE
additive manufacturing - remove module headers in EOC sections

### ISSUE THREAD

**Issue by lwtchu** [openstax/recipes#123]
![Screen Shot 2021-10-19 at 9 29 39 AM](https://user-images.githubusercontent.com/11299125/137970687-09df91ff-dc4c-418c-87c8-1b13f78daf92.png)

can we remove this injected text from the recipe? thank you~

**Comment by wilkus27** [comment]
### Information for tester

Recipe is merged to main, not released yet.

**Comment by MartaSztuka** [comment]
##### PASSED
![Screenshot from 2021-11-04 11-43-33](https://user-images.githubusercontent.com/47241114/140300493-ee3e8e6c-7fb0-4279-b1af-4f778fd4db09.png)
![Screenshot from 2021-11-04 11-43-43](https://user-images.githubusercontent.com/47241114/140300506-21f52b3b-da3f-40a6-8901-217d1171e1b8.png)
