### ISSUE TITLE
Psychology recipe

### ISSUE THREAD

**Issue by wilkus27** [openstax/recipes#153]
Content: `col31502` cnx.org

**Comment by wilkus27** [comment]
### Information for tester

Recipe is merged to main branch, but not released yet.

**Comment by MartaSztuka** [comment]
@wilkus27 Splash images display page-wide in 5, 7, 8, 10, 11, 14, 15, 16 in 4th it splits in 3 pages
##### 4th Chapter
![Screenshot from 2021-11-18 11-53-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1a8533c7-81bf-4b64-b6f9-535297ab25ec)
##### 5th Chapter (other listed chapters look the same)
![Screenshot from 2021-11-18 11-57-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b7f50c1a-75d0-48dd-b17a-4868edef7c7d)

**Comment by MartaSztuka** [comment]
#### Elements in book that are ok
##### Contents
![Screenshot from 2021-11-18 13-25-55.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7fb4f4be-df4d-4e84-9098-c41db218fdb3)
##### Preface
![Screenshot from 2021-11-18 13-26-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/18e878e8-6e11-4dc0-8fec-94c3bbd5e16b)
##### Chapter outline
![Screenshot from 2021-11-18 13-26-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4d7ce2ff-ec0b-4790-88d2-2337da54a5a7)
##### Link to learning
![Screenshot from 2021-11-18 13-27-16.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/40af484f-a2f9-45c6-b608-2eefcd0695d9)
##### Figure
![Screenshot from 2021-11-18 13-27-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bd449d19-65df-4c18-b3ca-556f21a6f74c)
##### Notes
![Screenshot from 2021-11-18 13-28-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a8edcb53-2893-4e39-9aa4-05dba1c6325a)![Screenshot from 2021-11-18 13-28-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fb938038-bd0d-42df-b598-942079cb967b)
##### Key terms
![Screenshot from 2021-11-18 13-29-25.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3aaa1f6e-6329-4a7c-99a3-dc23c82885c4)
##### Summary
![Screenshot from 2021-11-18 13-29-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fd000529-a85e-4159-b932-5b8f2edff2c1)
##### Review quastions
![Screenshot from 2021-11-18 13-30-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f28ba582-926e-49ae-bc90-2606a4b15d5e)
##### Critical thinking questions
![Screenshot from 2021-11-18 13-30-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/11544605-782b-4efc-9254-b244f0ab48cd)
##### Table
![Screenshot from 2021-11-18 13-31-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a348f9f0-00e7-4b50-81c1-0acdfd7a9a86)
##### References
![Screenshot from 2021-11-18 13-32-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/208fa3d5-ecc2-4d0f-a567-3f82cad7fc8b)
##### Index
![Screenshot from 2021-11-18 13-33-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/55d480a4-f6eb-480d-897f-8abfae395cf3)

**Comment by lwtchu** [comment]
I'll open a card for the CMs - thank you

**Comment by lwtchu** [comment]
@wilkus27 @MartaSztuka actually curious - did y'all generate with psychology 1e or 2e?

**Comment by wilkus27** [comment]
@lwtchu We used this collection `col31502`, I guess it is 2e. Should we also check 1e?

**Comment by lwtchu** [comment]
@wilkus27 no ! just want to double check. thank you though
