### ISSUE TITLE
Recipe for Introduction to Business

### ISSUE THREAD

**Issue by wilkus27** [openstax/recipes#158]
**Content:** `col25734   cnx.org`
Edit: https://github.com/openstax/osbooks-introduction-business

**Comment by wilkus27** [comment]
### Information for tester

Recipe is merged to main, but not released yet.

**Comment by wilkus27** [comment]
Can't be tested until content problem will be fixed.

When trying to generate PDF it stops on this step:

![image](https://user-images.githubusercontent.com/40228854/142898570-d055413f-1790-4d91-b78e-80b4137a5166.png)

Here is a description of the problem: https://katalysteducation.slack.com/archives/C022NETP39N/p1637596308478900?thread_ts=1637588594.472600&cid=C022NETP39N

**Comment by lwtchu** [comment]
Content changes are with the CMs and pending GitHub migration. I've let them know to alert you once they are done

**Comment by wilkus27** [comment]
Content problems are fixed now. Book is moved to github. I added link to it to issue description.

**Comment by MartaSztuka** [comment]
@wilkus27 Random figures are too big, might be content issue.
![Screenshot from 2022-01-12 14-39-01.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0c8b049a-43b2-426b-9eef-23fbc9cc9615)
#### PASSED
###### Contents
![Screenshot from 2022-01-12 14-19-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5b1d477c-7cc0-427d-99f1-13d0c1615490)
###### Preface
![Screenshot from 2022-01-12 14-21-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/99398659-7da7-4919-a58f-7bd0a846c5a3)
###### Chapter outline
![Screenshot from 2022-01-12 14-22-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3b77201e-9ad9-4bcd-9044-cef3d21f1f3a)
###### Figure
![Screenshot from 2022-01-12 14-25-34.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f0dcd428-93ee-445b-bbec-f68e80786bb8)
###### Table
![Screenshot from 2022-01-12 14-25-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bac53fa2-6659-4f80-8d44-f0fc708cc19c)
###### Notes
![Screenshot from 2022-01-12 14-26-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/986b21d7-fb81-4eb9-807e-fe1a54cc5a33)![Screenshot from 2022-01-12 14-26-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f8b470a5-8eb4-499e-bc1b-4f53fdf68b28)
###### Footnote
![Screenshot from 2022-01-12 14-37-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b53e4001-50de-48f6-8aeb-08dc3dbdea7d)
###### Key terms
![Screenshot from 2022-01-12 14-30-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/78553e64-4cd5-4b94-a6ea-5c31ad18ece7)
###### Summary
![Screenshot from 2022-01-12 14-32-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6da722a3-22b7-4175-bfea-40e3d6e50ce2)
###### Preparing for Tomorrow's Workplace Skills
![Screenshot from 2022-01-12 14-33-11.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7dcc0667-161c-4f08-a9ed-8c0c86e56ae0)
###### Ethics Activity/Working the Net
![Screenshot from 2022-01-12 14-34-31.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d1c23793-95bb-43fc-8db8-c8adaed723a9)
###### Critical Thinking Case/Hot Links Address Book
![Screenshot from 2022-01-12 14-35-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/288e0295-8d44-4a96-a04a-1a0fe82545b8)![Screenshot from 2022-01-12 14-35-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4190e922-3dd1-4244-9866-841ae8848b03)
###### Appendix
![Screenshot from 2022-01-12 14-36-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ec725926-5ef7-49b5-bd14-4b1019e6c584)
###### Index
![Screenshot from 2022-01-12 14-37-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4f586e54-4db4-4830-bf92-746ec7ff4729)
###### References
![Screenshot from 2022-01-12 14-38-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2686d09d-07ce-4cd2-beab-d5c79bfbcb94)

**Comment by wilkus27** [comment]
@lwtchu problems with figures that Marta mentioned are content issues.

**Comment by wilkus27** [comment]
Discussed with Larissa. Figures will be fixed in the content. I'm closing the issue.
