### ISSUE TITLE
Recipe for Polish U-Phisics

### ISSUE THREAD

**Issue by wilkus27** [openstax/recipes#179]
- vol1: `col23946   cnx.org`
- vol2: `col25244   cnx.org`
- vol3: `col25571   cnx.org`

**Comment by wilkus27** [comment]
#### Information for tester

Recipe is merged to main, not released yet.

**Comment by MartaSztuka** [comment]
@wilkus27 Leading between chapter and title is too narrow in cases like this one:
![Screenshot from 2021-12-16 15-44-13.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3533fba4-6dc1-424f-acde-0ef71995e36d)

#### PASSED
###### Contents
![Screenshot from 2021-12-16 15-38-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c1380c2b-7cb6-480c-bdf1-df08988369ce)
###### Preface
![Screenshot from 2021-12-16 15-39-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/76091a0c-9717-44ee-8fdf-6803a8f98c95)
###### Chapter outline
![Screenshot from 2021-12-16 15-46-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8e253b32-e099-4115-b4b6-b8edaa9e6d8d)
###### Figure
![Screenshot from 2021-12-16 15-47-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/54576b65-69b9-401c-b36e-c6487befd3c4)
###### Table
![Screenshot from 2021-12-16 15-47-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ac72d8b4-537e-4c69-b783-1ffd7a3afaac)
###### Notes
![Screenshot from 2021-12-16 15-48-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4db79a46-e8a8-4b9f-8936-fdb9d39c36c4)
###### Example
![Screenshot from 2021-12-16 15-49-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cea7c2d8-d3a8-475b-bcef-0e217f151bd6)
###### Sprawdź czy rozumiesz
![Screenshot from 2021-12-16 15-49-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/72ef7038-adc2-4b0f-8091-a08eb4df7e1c)
###### Key terms
![Screenshot from 2021-12-16 15-51-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4f78cf79-991e-4ce1-b729-a32f04934974)
###### Key equations
![Screenshot from 2021-12-16 15-52-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c0e2ca35-6459-4601-a704-6f4fd86b5b1f)
###### Review questions
![Screenshot from 2021-12-16 15-52-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2d9e9788-bfa5-4adc-a046-ba709721bbf1)
###### Appendix
![Screenshot from 2021-12-16 15-54-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/395130c8-498f-420c-bdf3-4cb473b6c73f)
###### Index
![Screenshot from 2021-12-16 15-55-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d31bbff3-3c6f-469d-bf32-251d65a5e648)![Screenshot from 2021-12-16 15-55-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/08773722-7bd8-49d1-a8bd-26592536bed5)![Screenshot from 2021-12-16 15-55-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5748ba0a-40b1-4c70-a69b-34376d33b3bc)

**Comment by wilkus27** [comment]
Because problem with title:

![image](https://user-images.githubusercontent.com/40228854/150305281-70a44217-afc0-49e3-97b3-11af714369be.png)

is the only case where it looks bad (because of polish letter Ź) we decided to not fixing that. I'm closing the issue.
