### ISSUE TITLE
change request: underline and double-underline accessibility for screenreader bits to go with the actual underlined text

### ISSUE THREAD

**Issue by lwtchu** [openstax/recipes#194]
#137 - original issue 
https://openstax.slack.com/archives/CH5514N57/p1641485639002300 - thread for context

![image](https://user-images.githubusercontent.com/11299125/148435647-39e32a38-c83b-4c91-a5d9-a496252992af.png)

Please move the `span` into the `<u>` tag and add another `span` to indicate the underline end before the closing `<u>` tag. We'll probably need a style change to suppress the second added text(?) 

`<u data-effect="underline"><span data-screenreader-only="true">underline</span>texty texty<span data-screenreader-only="true">end underline</span></u>`

Same for double underline.

**Comment by kswanson33** [comment]
did we settle on what's happening with the beginning & end of the underline?

**Comment by lwtchu** [comment]
@kswanson33 not yet sorry i think @Stackblocks was last seen trying to fire up the laptop :joy:

**Comment by Stackblocks** [comment]
Taking a look at this now 😄

**Comment by Stackblocks** [comment]
Looking at a copy of English Comp generated today using current code and content:

Like y'all said above, announcements are currently made at the start of the targeted span with no closing note, which is OK for single word targets, but for longer phrases like the second example here it is less than clear, especially when there is text beyond the targeted phrase in the same sentence.

## Example 1
>"The `underline` bus `double underline` leaves"

![image](https://user-images.githubusercontent.com/12678235/149994604-f89fc4fe-384e-454d-bc8e-2d0912237489.png)

## Example 2
>"`underline` Basketball and wrestling `double underline` are my favorite sports"

![image](https://user-images.githubusercontent.com/12678235/149995996-564681f7-2ec5-4b81-afe8-b9a9464b1828.png)

**Comment by Stackblocks** [comment]
It doesn't announce Term bolding at all with the out of the box settings.

**Comment by lwtchu** [comment]
:| hm NOT A NEW PROBLEM WE UNCOVERED

**Comment by lwtchu** [comment]
@kswanson33 let's go with the option outline in the issue and we can test. the text will be hidden right? since it has the same data atrribute

**Comment by kswanson33** [comment]
yes! so to confirm that's underline/end underline, double underline/end double underline. any thoughts on using "end markup" instead?

**Comment by Stackblocks** [comment]
Span has been moved into `<u>`, and there is now a termination line for the screen reader 🎉 

![2022-01-21_13-46-19](https://user-images.githubusercontent.com/12678235/150590854-17e7d202-a39f-4639-883d-87719c264f77.png)
