### ISSUE TITLE
Make Public Domain, Student Sample, and Annotated text styling detectable for screen readers

### ISSUE THREAD

**Issue by lwtchu** [openstax/recipes#195]
@openstaxalina commented on [Tue Dec 07 2021](https://github.com/openstax/unified/issues/1768)

# Description
This is needed for Writing Guide with Handbook, so that screen readers can detect the changes made as part of https://github.com/openstax/unified/issues/1723

(Note: might make sense to do this at the same time as https://github.com/openstax/unified/issues/1740)

# Acceptance Criteria
- screen reader says something like "Public Domain Text" when content with class `public-domain` starts 
- screen reader says something like "End Public Domain Text" when content with class `public-domain` ends

- screen reader says something like "Student Sample Text" when content with class `student-sample` starts 
- screen reader says something like "End Student Sample Text" when content with class `student-sample` ends

- screen reader says something like "Annotated Text" when content with class `annotation-text` starts 
- screen reader says something like "End Annotated Text" when content with class `annotation-text` ends

**Comment by Stackblocks** [comment]
All markers announce both the opening and closure of the appropriate text
