### ISSUE TITLE
Recipe for Business Ethics

### ISSUE THREAD

**Issue by wilkus27** [openstax/recipes#203]
CONTENT:
Business Ethics - https://github.com/openstax/osbooks-business-ethics
Business Law - https://github.com/openstax/osbooks-business-law
Intellectual Property - https://github.com/openstax/osbooks-introduction-intellectual-property

**Comment by wilkus27** [comment]
Waiting for a content changes in Business Law. Examples should be removed there.

**Comment by wilkus27** [comment]
Waiting for information abot content for Business Ethics and Intellectual property.

**Comment by MartaSztuka** [comment]
#### PASSED
##### Business Law
###### Contents
![Screenshot from 2022-01-19 15-10-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ff35fbe9-5d3c-4300-823e-83109a1492b0)
###### Preface
![Screenshot from 2022-01-19 15-10-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c6644b7d-a5a0-4388-a1f5-901341a86afc)
###### Chapter outline
![Screenshot from 2022-01-19 15-11-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/82dad1fa-e59d-4980-a0fa-50b9793d8fd3)
###### Figure
![Screenshot from 2022-01-19 15-11-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/92530e2d-8fa3-4bc0-a4de-4704f29bcede)
###### Table
![Screenshot from 2022-01-19 15-12-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2c61b26e-6643-40e3-a012-93e211e0e539)
###### Assessment Questions
![Screenshot from 2022-01-19 15-13-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/18f24ee5-f31a-4ef4-a077-dfde55848ad4)
###### Endnotes
![Screenshot from 2022-01-19 15-14-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a8a0f1e9-f73b-4d0a-a66b-5ccd36605835)
###### Answer Key
![Screenshot from 2022-01-19 15-15-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c51a58f5-e993-4e71-83c9-83a3af477b49)
###### Index
![Screenshot from 2022-01-19 15-15-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/51e162e3-8008-40c5-88e4-57e647526a7e)

**Comment by MartaSztuka** [comment]
#### PASSED
##### Introduction to Intellectual Property 
###### Contents
![Screenshot from 2022-01-20 09-40-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/baf0197c-0e38-4f08-ba02-d0f8ff9d2424)
###### Preface and Foreword
![Screenshot from 2022-01-20 09-41-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7e95b806-cf63-4b43-af5d-e4009213b362)
###### Chapter outline
![Screenshot from 2022-01-20 09-42-51.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7525e4f0-a036-4656-971b-45bef02085a3)
###### Figure
![Screenshot from 2022-01-20 09-43-12.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/702652c7-5d45-4976-9b23-e2065fa9bd5f)
###### Table
![Screenshot from 2022-01-20 09-44-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/397a5f82-3aff-41d2-b105-f158681b0711)
###### Footnote
![Screenshot from 2022-01-20 09-43-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cf0b015f-9616-4af3-92c1-c7247f165c8f)
###### Assessment Questions
![Screenshot from 2022-01-20 09-44-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5bb62c22-cb18-4521-a606-2fab76a9f76e)
###### Glossary
![Screenshot from 2022-01-20 09-45-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/073ba0a3-4eb5-4c25-98d5-3abfd947a780)
###### Answer Key
![Screenshot from 2022-01-20 09-45-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9a5ac876-2339-416d-b1b7-fe25e49746af)
###### Index
![Screenshot from 2022-01-20 09-46-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/249b940c-ba87-4c34-87db-593fa5c4cebf)

**Comment by MartaSztuka** [comment]
@wilkus27 in Intellectual Property when first module starts with an image Introduction header and module is divided.
![Screenshot from 2022-01-20 09-47-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7394b707-3131-4e71-a76c-307ce7ede6bf)

**Comment by wilkus27** [comment]
@lwtchu I checked and in all chapters Introduction pages are empty. There is only title **Introduction** there. Is it intentionall? Or some text will be added later?

**Comment by MartaSztuka** [comment]
#### PASSED
##### Business Ethics
###### Contents
![Screenshot from 2022-01-21 16-37-29.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6bf853ae-2703-44a2-af24-f86d32442cac)
###### Preface
![Screenshot from 2022-01-21 16-38-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/dd3d8f23-eabd-4f4e-b399-61fb30223edf)
###### Chapter outline
![Screenshot from 2022-01-21 16-39-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/172e41a9-eecd-4fc9-81e1-92c4c1c08262)
###### Figure
![Screenshot from 2022-01-21 16-39-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b197ca98-c13b-48fe-baba-6892ff6d1d6f)
###### Table
![Screenshot from 2022-01-21 16-45-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c051ee8c-c8cf-47d7-8305-c0f3f77fc539)
###### Link to Learning
![Screenshot from 2022-01-21 16-39-59.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a5d6204a-498a-45a2-8e5e-a924638b9fb9)
###### Cases from the Real World
![Screenshot from 2022-01-21 16-40-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f08feb0a-0926-45d1-b425-39ad42cabaf6)
###### What would you do?
![Screenshot from 2022-01-21 16-41-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a1abd083-3f55-4609-b5d0-914464dd9035)
###### Ethics across Time and Cultures
![Screenshot from 2022-01-21 16-42-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/2890a83c-97bb-47cd-bd3b-5280076857f6)
###### Key Terms
![Screenshot from 2022-01-21 16-43-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/72e63ea7-31ad-4fef-b97b-8448baa73403)
###### Summary
![Screenshot from 2022-01-21 16-43-39.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/506a233f-fb4e-4ac4-b1e5-49afbb263ca4)
###### Assessment Questions
![Screenshot from 2022-01-21 16-44-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5d25cb5d-3214-41f6-b530-3f70aa99c1a4)
###### Endnotes
![Screenshot from 2022-01-21 16-44-41.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c436c229-359d-476a-9ae1-97592dcb66c7)
###### Answer Key
![Screenshot from 2022-01-21 16-45-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ccd77844-1f3e-43e0-9396-f0d3365b56d9)
###### Index
![Screenshot from 2022-01-21 16-45-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cf5c5ce8-1e7f-4ac3-8fb2-48a7d01c85ff)

**Comment by wilkus27** [comment]
**Decision about https://github.com/openstax/recipes/issues/203#issuecomment-1017245720**: Introduction pages without content in Intellectual Property are intentional. We don't worry about additional empty spaces. 

I'm closing an issue.
