### ISSUE TITLE
College Physics is missing BakeFolio

### ISSUE THREAD

**Issue by ajluk** [openstax/recipes#205]
During working on Prince update I noticed that the folio parts baked in kitchen (preface, Access for free... ) are missing in the pdf: 
![image](https://user-images.githubusercontent.com/55203598/149363817-3b094e73-9d01-4626-9058-793fb4d45e41.png)

**Comment by MartaSztuka** [comment]
#### PASSED
![Screenshot from 2022-01-14 11-39-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c23bbfca-0558-45aa-b357-ae46e9247227)![Screenshot from 2022-01-14 11-39-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/370e1945-90b1-4e37-b90e-3cb9a04fbb79)
