### ISSUE TITLE
upgrade chemistry recipe to newer  version (6 or 7?)  to support i18n

### ISSUE THREAD

**Issue by lwtchu** [openstax/recipes#53]
hi in order for us to utilize the cool spanish words karina will input here https://github.com/openstax/kitchen/issues/237
we need to make sure chemistry recipe can use the internationalization stuff

assigning @kswanson33 since I think you're the author (and not JP)

**Comment by Stackblocks** [comment]
- [x] Displays OK in up-to-date code on local branch

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/bdd2eff4-ca60-4a74-965a-eac76bb34eb7)
